### ISSUE TITLE
Validate copyright string and update footer

### ISSUE THREAD

**Issue by tsmcgrath** [tsmcgrath/BMPStaging#14]
© TPWD 2020. All Rights Reserved.

**Comment by tmbroad** [comment]
Looks good.
Not sure if I am supposed to do anything more than ok it?

**Comment by tsmcgrath** [comment]
Tyson, please validate what you want as the copyright text with Megan and let me know. Then I'll replace the out-of-date string in the footer. Also, if you want a link in the footer to go to TPWD or anywhere, let me know what the link is.

[© TPWD 2020. All Rights Reserved.](https://tpwd.texas.gov/)

**Comment by tmbroad** [comment]
Megan had to have an appendectomy the other day. She will be back on-line Monday, she says.

**Comment by tsmcgrath** [comment]
Tyson validated the above string in Slack.
https://wanderfeastteam.slack.com/archives/GTMKEHSRF/p1596592525003700?thread_ts=1596583194.003400&cid=GTMKEHSRF

**Comment by tsmcgrath** [comment]
All copyright strings updated.
