### ISSUE TITLE
Watersheds Index Page

### ISSUE THREAD

**Issue by tsmcgrath** [tsmcgrath/BMPStaging#26]
Fix? Remove?

https://tsmcgrath.github.io/BMPStaging/WatershedsIndex.html

It is an index page on all the title pages and would have to be removed from all if removal is what is decided.

**Comment by tmbroad** [comment]
I do not see that it is necessary. Remove.

**Comment by tsmcgrath** [comment]
From Megan: Yes, remove.  It’s not going to be useful until we have time to make BMPS specific to each watershed. Also remove other references and the EDU map on the home page.

**Comment by tsmcgrath** [comment]
Fixed.
